# Basics

In [2]:
# create an array
import numpy as np
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [3]:
arr1[0]=12.6
arr1

array([12,  2,  3])

In [4]:
arr1.ndim



1

In [5]:
arr2=np.array([[1,2,3],[3,4,5]])
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [6]:
arr2.ndim


2

In [7]:
arr2.shape

(2, 3)

In [8]:
arr3=np.array([[[2,3,4],[3,4,5],[4,5,7]],[[1,2,3],[3,4,5],[4,5,6]],[[2,3,4],[3,4,5],[4,6,7]]])
arr3

array([[[2, 3, 4],
        [3, 4, 5],
        [4, 5, 7]],

       [[1, 2, 3],
        [3, 4, 5],
        [4, 5, 6]],

       [[2, 3, 4],
        [3, 4, 5],
        [4, 6, 7]]])

In [9]:
arr3.ndim


3

In [10]:
arr4=np.array([[[[1, 2, 3, 4, 5],
                             [6, 7, 8, 9, 10],
                             [11, 12, 13, 14, 15]],
                            [[16, 17, 18, 19, 20],
                             [21, 22, 23, 24, 25],
                             [26, 27, 28, 29, 30]]],
                           [[[31, 32, 33, 34, 35],
                             [36, 37, 38, 39, 40],
                             [41, 42, 43, 44, 45]],
                            [[46, 47, 48, 49, 50],
                             [51, 52, 53, 54, 55],
                             [56, 57, 58, 59, 60]]]])
arr4

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15]],

        [[16, 17, 18, 19, 20],
         [21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30]]],


       [[[31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40],
         [41, 42, 43, 44, 45]],

        [[46, 47, 48, 49, 50],
         [51, 52, 53, 54, 55],
         [56, 57, 58, 59, 60]]]])

In [11]:
arr4=np.array([[[[1,1],[1,1],[1,1]],[[1,1],[1,2],[1,2]]],[[[2,2],[1,2],[2,2]],[[4,4],[2,3],[4,4]]]])
arr4

array([[[[1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 2],
         [1, 2]]],


       [[[2, 2],
         [1, 2],
         [2, 2]],

        [[4, 4],
         [2, 3],
         [4, 4]]]])

In [12]:
arr4.ndim


4

In [13]:
arr5=np.array([[[[5],[6],[7]],[[5],[7],[8]]],[[[8],[9],[9]],[[4],[2],[1]]]])
arr5

array([[[[5],
         [6],
         [7]],

        [[5],
         [7],
         [8]]],


       [[[8],
         [9],
         [9]],

        [[4],
         [2],
         [1]]]])

In [14]:
arr5.shape

(2, 2, 3, 1)

In [15]:
arr=np.array([2,3,4],dtype="complex")
arr


array([2.+0.j, 3.+0.j, 4.+0.j])

In [16]:
arr.imag

array([0., 0., 0.])

In [17]:
arr.imag=np.array([6,7,8])
arr

array([2.+6.j, 3.+7.j, 4.+8.j])

In [18]:
arr.real

array([2., 3., 4.])

In [19]:
arr=np.array([7,9,0,0,1,0],dtype="bool")

In [20]:
arr

array([ True,  True, False, False,  True, False])

In [21]:
arr1=np.zeros(5)

In [22]:
arr1

array([0., 0., 0., 0., 0.])

In [23]:
arr1=np.zeros((2,3))

In [24]:
arr1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
arr1=np.ones((3,3))

In [26]:
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
arr1=np.empty((3,4))
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
arr1=np.full((2,2),99,dtype="int64")
arr1

array([[99, 99],
       [99, 99]])

In [29]:
arr2=np.full_like(arr1,22)
arr2

array([[22, 22],
       [22, 22]])

In [30]:
arr2=np.zeros_like((2,3))
arr2

array([0, 0])

In [31]:
arr2=np.random.rand(2,3)
arr2

array([[0.01064332, 0.00135067, 0.4203152 ],
       [0.21706478, 0.61741964, 0.38219255]])

In [32]:
#within range 0-7(3 rows and 4 column)
np.random.randint(0,7,(3,4))

array([[2, 0, 1, 0],
       [2, 2, 0, 4],
       [4, 6, 6, 5]])

In [33]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [35]:
np.linspace(2,6,3)

array([2., 4., 6.])

In [36]:
import numpy as np

In [37]:
data=np.loadtxt('data.txt',skiprows=1)
data

array([[33., 55.],
       [44., 66.],
       [55., 88.]])

In [38]:
data.shape

(3, 2)

In [39]:
data.ndim

2

In [40]:
mark1,mark2=np.loadtxt('data.txt',skiprows=1,unpack=True)

In [41]:
print(mark1)
print(mark2)

[33. 44. 55.]
[55. 66. 88.]


In [42]:
# fromfunction
np.fromfunction(lambda i,j:i+j,(2,2))


array([[0., 1.],
       [1., 2.]])

In [43]:
# indexing and slicing
arr1=np.array([[[2,3,4],[2,9,4]],[[1,2,3],[4,5,6]]])

In [44]:
arr1[1]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr2=np.array([[3,4,5,6],[1,2,3,4]])
arr2

array([[3, 4, 5, 6],
       [1, 2, 3, 4]])

In [46]:
arr2[0]

array([3, 4, 5, 6])

In [47]:
arr2[1]

array([1, 2, 3, 4])

In [48]:
arr2[-1]

array([1, 2, 3, 4])

In [49]:
arr2[1][1]

2

In [50]:
arr2[0,1]

4

In [51]:
arr3=np.random.randint(2,8,(2,3,4))
arr3

array([[[7, 2, 5, 3],
        [3, 5, 3, 3],
        [7, 2, 4, 7]],

       [[4, 7, 5, 2],
        [7, 5, 2, 6],
        [3, 6, 2, 7]]])

In [52]:
arr=np.full((2,3,4),8)
arr

array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

In [53]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr_slice=arr[0:5]

In [55]:
arr=np.arange(1,10)

In [56]:
np.random.randint(1,10,(1,10))

array([[7, 2, 5, 8, 8, 8, 1, 2, 4, 8]])

In [57]:
li=[1,2,3,4,5,6,7,8,9,10]
li

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [58]:
li_slice=li[0:5]
li_slice

[1, 2, 3, 4, 5]

In [59]:
arr_slice

array([1, 2, 3, 4, 5])

In [60]:
arr_slice[0]=5

In [61]:
arr_slice

array([5, 2, 3, 4, 5])

In [62]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
li_slice[0]=5
li_slice

[5, 2, 3, 4, 5]

In [64]:
li

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [65]:
a1=np.random.randint(1,10,(2,3,4))
a1

array([[[1, 3, 2, 9],
        [8, 1, 2, 3],
        [5, 6, 8, 6]],

       [[7, 5, 9, 3],
        [9, 2, 4, 7],
        [2, 8, 5, 3]]])

In [66]:
b=np.array([[3,4,5,5,5],[2,5,6,3,3],[1,3,7,1,2]])
b

array([[3, 4, 5, 5, 5],
       [2, 5, 6, 3, 3],
       [1, 3, 7, 1, 2]])

In [67]:
b[:2,1:]

array([[4, 5, 5, 5],
       [5, 6, 3, 3]])

In [68]:
# start:end:step
b[:,::2]

array([[3, 5, 5],
       [2, 6, 3],
       [1, 7, 2]])

In [69]:
# masking
arr=b>4
b[arr]

array([5, 5, 5, 5, 6, 7])

### scalar operations

In [70]:

b

array([[3, 4, 5, 5, 5],
       [2, 5, 6, 3, 3],
       [1, 3, 7, 1, 2]])

In [71]:
b+2

array([[5, 6, 7, 7, 7],
       [4, 7, 8, 5, 5],
       [3, 5, 9, 3, 4]])

In [72]:
b-2

array([[ 1,  2,  3,  3,  3],
       [ 0,  3,  4,  1,  1],
       [-1,  1,  5, -1,  0]])

In [73]:
b*2

array([[ 6,  8, 10, 10, 10],
       [ 4, 10, 12,  6,  6],
       [ 2,  6, 14,  2,  4]])

In [74]:
b

array([[3, 4, 5, 5, 5],
       [2, 5, 6, 3, 3],
       [1, 3, 7, 1, 2]])

In [75]:
a=np.array([[1,2],[3,5]])
b=np.array([[9,7],[6,8]])
print(a)
b

[[1 2]
 [3 5]]


array([[9, 7],
       [6, 8]])

In [76]:

np.dot(a,b)

array([[21, 23],
       [57, 61]])

In [77]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [78]:
a==b


array([[False, False],
       [False, False]])

In [79]:
np.logical_or(a,b)

array([[ True,  True],
       [ True,  True]])

In [80]:
np.sum(a)

11

In [81]:
np.sum(a,axis=1)

array([3, 8])

In [82]:
np.min(a)

1

In [83]:
# reorganising
ar=np.array([[1,2,3,4,5],[2,3,4,5,6]])

In [84]:
ar


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [85]:
ar.shape

(2, 5)

In [86]:
ar.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 2],
       [3, 4],
       [5, 6]])

In [87]:
ar.reshape(1,10)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6]])

In [88]:
ar.reshape(2,5,1)

array([[[1],
        [2],
        [3],
        [4],
        [5]],

       [[2],
        [3],
        [4],
        [5],
        [6]]])

In [89]:
# repeat an array
arr=np.array([1,2,3,4,5])
np.repeat(arr,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [90]:
arr1=np.array([[2,3,4],[3,4,5]])

In [91]:
np.repeat(arr1,2,axis=0)

array([[2, 3, 4],
       [2, 3, 4],
       [3, 4, 5],
       [3, 4, 5]])

In [92]:
# vertical stack
v1=np.array([1,2,3,4])
v2=np.array([3,4,5,6])
arr=np.vstack([v1,v2,v1,v1,v1])
arr

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [93]:
np.hstack([v1,v2])

array([1, 2, 3, 4, 3, 4, 5, 6])

In [94]:
# squeeze reduce dimension
np.squeeze(arr)

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [95]:
arr=np.zeros((4,3,2))
arr


array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [96]:
np.expand_dims(arr,axis=(0,2)).shape

(1, 4, 1, 3, 2)

In [97]:
arr

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [98]:
v1

array([1, 2, 3, 4])

In [101]:
print(v1.argmin())
print(v1)

0
[1 2 3 4]


In [100]:
v1.argmax()

3

In [103]:
arr1=np.arange(16).reshape(4,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [104]:
np.argmin(arr1)

0

In [105]:
np.argmax(arr1)

15

In [106]:
np.min(arr1)

0

In [107]:
np.max(arr1)

15

In [109]:
arr = np.array([3, 7, 4, 2, 5])

# Using np.min() to find the minimum value
minimum_value = np.min(arr)
print("Minimum value:", minimum_value)

# Using np.argmin() to find the index of the minimum value
index_of_minimum = np.argmin(arr)
print("Index of minimum value:", index_of_minimum)

Minimum value: 2
Index of minimum value: 3


In [110]:
arr.size

5

In [112]:
arr.itemsize

8

In [113]:
arr


array([3, 7, 4, 2, 5])

In [114]:
arr.shape

(5,)

In [115]:
arr.reshape(1,5)

array([[3, 7, 4, 2, 5]])

In [117]:
arr.min()

2

In [118]:
arr.sum()

21

In [119]:
arr.max()

7

In [122]:
a=np.linspace(5,15,10)

In [123]:
a

array([ 5.        ,  6.11111111,  7.22222222,  8.33333333,  9.44444444,
       10.55555556, 11.66666667, 12.77777778, 13.88888889, 15.        ])

In [128]:
a.size

10

In [129]:
a.reshape(2,5)

array([[ 5.        ,  6.11111111,  7.22222222,  8.33333333,  9.44444444],
       [10.55555556, 11.66666667, 12.77777778, 13.88888889, 15.        ]])

In [132]:
a.reshape(2,5)

array([[ 5.        ,  6.11111111,  7.22222222,  8.33333333,  9.44444444],
       [10.55555556, 11.66666667, 12.77777778, 13.88888889, 15.        ]])

In [137]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [138]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [141]:
a=np.full((3,3),66)
a

array([[66, 66, 66],
       [66, 66, 66],
       [66, 66, 66]])

In [142]:
np.full_like(a,10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [143]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [145]:

a = np.zeros((2, 3))  # Creates a 2x3 array filled with zeros
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [146]:

b = np.empty((2, 3))  
b


array([[0., 0., 0.],
       [0., 0., 0.]])

In [147]:
b = np.empty((2, 3))  
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [148]:
np.random.rand(2,3)

array([[0.20613176, 0.32778016, 0.5393724 ],
       [0.34775337, 0.93308583, 0.20284076]])

In [151]:
np.random.rand(2,3,4)

array([[[0.65097002, 0.60659462, 0.84781091, 0.72531331],
        [0.20044046, 0.96322944, 0.74603964, 0.23797716],
        [0.59261837, 0.4276851 , 0.13755618, 0.5785475 ]],

       [[0.34350491, 0.07304739, 0.89883598, 0.48526352],
        [0.76488244, 0.62335748, 0.734673  , 0.10405895],
        [0.2141138 , 0.87592336, 0.6354098 , 0.45250676]]])

In [152]:
np.random.rand(2)


array([0.65643587, 0.08853262])

In [180]:
set1=np.random.randint(2,10,(2,2,3,4))
set1

array([[[[5, 9, 6, 2],
         [6, 7, 2, 3],
         [9, 7, 3, 9]],

        [[4, 9, 4, 8],
         [9, 6, 5, 5],
         [4, 7, 3, 6]]],


       [[[5, 7, 8, 7],
         [7, 4, 6, 7],
         [3, 4, 9, 2]],

        [[7, 7, 6, 4],
         [8, 5, 6, 8],
         [9, 3, 6, 2]]]])

In [160]:
set1.min()

2

In [161]:
set1.argmin()

6

In [162]:
np.argmin(set1)

6

In [181]:
np.vstack(set1)


array([[[5, 9, 6, 2],
        [6, 7, 2, 3],
        [9, 7, 3, 9]],

       [[4, 9, 4, 8],
        [9, 6, 5, 5],
        [4, 7, 3, 6]],

       [[5, 7, 8, 7],
        [7, 4, 6, 7],
        [3, 4, 9, 2]],

       [[7, 7, 6, 4],
        [8, 5, 6, 8],
        [9, 3, 6, 2]]])

In [186]:
a=np.array([[1,2,3],[2,3,4],[3,4,5]])
a
           

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [187]:
b=np.array([[1,2,3],[2,3,4],[3,4,5]])
b

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [184]:
np.add(a,b)

array([[ 2,  4,  6,  8],
       [ 4,  6,  8, 12],
       [ 6,  8, 10, 16]])

In [188]:
np.dot(a,b)

array([[14, 20, 26],
       [20, 29, 38],
       [26, 38, 50]])

In [189]:
np.vstack([a,b])

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [190]:
np.hstack([a,b])

array([[1, 2, 3, 1, 2, 3],
       [2, 3, 4, 2, 3, 4],
       [3, 4, 5, 3, 4, 5]])

In [195]:
a[0:2,0:1]

array([[1],
       [2]])

In [196]:
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [200]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [201]:
np.sum(a,axis=1)

array([ 6,  9, 12])

In [205]:
np.transpose(a)

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [206]:
np.trace(a)

9

In [207]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [213]:
np.append(a,[[3,4,8]],axis=0)

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [3, 4, 8]])

In [214]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [215]:
b

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [217]:
np.insert(a,2,2,axis=0)

array([[1, 2, 3],
       [2, 3, 4],
       [2, 2, 2],
       [3, 4, 5]])

In [218]:
np.concatenate((a,b),axis=0)

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [219]:
np.split(a,3,axis=0)

[array([[1, 2, 3]]), array([[2, 3, 4]]), array([[3, 4, 5]])]

In [220]:
np.delete(a,2,axis=1)

array([[1, 2],
       [2, 3],
       [3, 4]])

In [222]:
np.std(a)

1.1547005383792515

In [223]:
np.linalg.det(a)

-7.401486830834414e-17

In [225]:
ev,evv=np.linalg.eig(a)
print(ev,evv)

[ 9.62347538e+00 -6.23475383e-01  1.78970268e-16] [[-0.38508979 -0.82767094  0.40824829]
 [-0.55951021 -0.14241368 -0.81649658]
 [-0.73393063  0.54284358  0.40824829]]


In [226]:
np.transpose(a)

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [227]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [229]:
np.random.randint(2,8,(4,4))

array([[5, 4, 2, 5],
       [5, 7, 2, 4],
       [7, 3, 5, 7],
       [3, 4, 4, 6]])